version: "3.8"

services:
  db:
    image: postgres:15
    container_name: qsd_postgres
    restart: always
    environment:
      POSTGRES_USER: qsd_admin
      POSTGRES_PASSWORD: qsd_password
      POSTGRES_DB: qsd_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: qsd_backend
    restart: always
    ports:
      - "8888:8080"
    environment:
      - DATABASE_URL=postgresql://qsd_admin:qsd_password@db:5432/qsd_db
      - PDF_STORAGE_DIR=/app/pdf_storage
    volumes:
      - ./backend/pdf_storage:/app/pdf_storage
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: qsd_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: qsd_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@qsd.com
      PGADMIN_DEFAULT_PASSWORD: QSDgris123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
